Merge with Master branch
xBimTeam/XbimGeometry pull request #322
Opened 2021-03-29 14:03 UTC by dmk-rib

2021-03-29 14:31 UTC, GeorgDangl requested changes

2021-03-29 14:31 UTC, GeorgDangl commented on Xbim.Geometry.Engine.Interop/XbimCustomAssemblyResolver.cs
>                                                                       // code base always points to the deployed DLL, which may be different to the executing Location because of Shadow Copying in the
The comment should be updated to refer to `Location` instead of `code base`

2021-03-29 14:31 UTC, GeorgDangl commented on Xbim.Geometry.Engine.Interop/XbimGeometryEngine.cs
> +            //XbimPrerequisitesValidator.Validate();
There's commented out code, with obsolete comments above. The comment says it's not necessary anymore, so this can probably be removed completely.

2021-03-29 14:31 UTC, GeorgDangl commented on Xbim.Geometry.Regression/BatchProcessor.cs
> +								    "IfcConnectedFaceSet"
Inconsitent formatting in this block, it's sometimes using spaces and sometimes tabs. That makes the code not well aligned.

2021-03-29 14:31 UTC, GeorgDangl commented on Xbim.Geometry.Regression/BatchProcessor.cs
> +                                // ents.Add(s.Instances[69512]);
Looks like an oversight from debugging and can probably be removed.

2021-03-29 14:31 UTC, GeorgDangl commented on Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs
> +        //private IXbimGeometryObject CallWithTimeout(IIfcGeometricRepresentationItem shape, ILogger logger, int booleanTimeOutMilliSeconds)
Lots of commented out code, can probably be removed. That's what Git is for😀

2021-03-29 14:31 UTC, GeorgDangl commented on Xbim.ModelGeometry.Scene/XbimEnvironment.cs
> +        ///// <summary>
Again lots of commented out code present, should be removed.

2021-03-29 14:31 UTC, GeorgDangl commented on Xbim.ModelGeometry.Scene/XbimEnvironment.cs
> +        //public static IEnumerable<string> InstalledRuntimes()
Again, commented out code which should not be kept around.

2021-03-29 14:51 UTC, GeorgDangl approved these changes

2021-05-20 04:45 UTC, dmk-rib commented
Have you a chance to take a look at this commit?

2021-06-16 10:53 UTC, jomijomi commented
Yeah, I'm also interested to see this in master. I have a couple of files that halts without this fix.
Best,
Mikael

2024-07-18 08:02 UTC, emilaz commented
Is anyone still maintaining this repo or is there a specific reason this is not merged into master?

2025-11-21 10:31 UTC, closed without merging